apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: aubg-gaming
  name: aubg-gaming
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: aubg-gaming
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: aubg-gaming
    spec:
      containers:
        - image: martykdv/aubg-gaming:latest
          name: aubg-gaming-v1
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
