apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-db
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: ${DB_NAME}
            - name: MYSQL_PASSWORD
              value: ${DB_PASSWORD}
            - name: MYSQL_ROOT_PASSWORD
              value: ${DB_PASSWORD}
            - name: MYSQL_USER
              value: ${DB_USER}
          image: mysql:latest
          name: mysql-db
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysqldata
      restartPolicy: Always
      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysqldata
status: {}
